/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'darjeeling' at '5/30/17 11:57 AM' with Gradle 3.0
 *
 * @author darjeeling, @date 5/30/17 11:57 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
